Repository sopt-makers/sopt-push-notification, pull requests merged in 2023-07, with the labels that each got.

#8 Feat/delivery failed job
  package-lock.json
  package.json
  serverless.yml
  src/constants/user.ts
  src/lambda.ts
  src/modules/dtoValidator.ts
  src/modules/logFactory.ts
  src/modules/messageFactory.ts
  src/modules/snsFactory.ts
  src/modules/tokenFactory.ts
  src/services/notificationService.ts
  src/services/userService.ts
  src/types/index.ts
  src/types/tokens.ts
Labels: size/XL

#6 토큰 등록, 해제
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  serverless.yml
  src/constants/response.ts
  src/constants/responseMessage.ts
  src/constants/status.ts
  src/constants/statusCode.ts
  src/constants/user.ts
  src/lambda.ts
  src/modules/dtoValidator.ts
  src/modules/logFactory.ts
  src/modules/messageFactory.ts
  src/modules/snsFactory.ts
  src/modules/tokenFactory.ts
  src/services/notificationService.ts
  src/services/userService.ts
  src/types/index.ts
  src/types/notifications.ts
  src/types/tokens.ts
Labels: feat, size/XXL

#10 토큰 삭제 파라미터 수정
  serverless.yml
  src/lambda.ts
  src/modules/dtoValidator.ts
  src/services/userService.ts
  src/types/index.ts
Labels: fix, size/L
