Repository sopt-makers/sopt-push-notification, pull requests merged in 2024-11, with the labels that each got.

#23 [FEAT] 알림 발송 시점 필드 추가
  src/modules/messageFactory.ts
Labels: size/S

#25 [INFRA] CI/CD 환경 구축
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
  package.json
Labels: size/L

#27 [HOTFIX] build, clean 명령어 분리
  package.json
Labels: size/XS

#29 [FIX] npm run clean & build 배포 스크립트에 포함되도록 수정
  package.json
Labels: size/XS
